name: autofix.ci
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - run: bun install
      - name: Fix lint issues

        run: bun run lint:fix
      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
        with:
          commit-message: "fix: lint issues"
